version: '3.7'
services:
  matterbridge:
    image: 42wim/matterbridge:stable
    restart: unless-stopped
    ports:
      - "4242:4242"
      - "4343:4343"
    volumes:
      - ./matterbridge:/etc/matterbridge
    entrypoint: ["/bin/matterbridge", "-debug", "-conf", "/etc/matterbridge/matterbridge.toml"]