name: DEPLOY

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: 'Clone Repo'
        uses: actions/checkout@v1

      - name: 'Build'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'build --stacktrace'

      - name: 'Publish to BinTray'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'publishSibylPublicationToBintrayRepository -Pnodryrun --stacktrace'
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}

      - name: 'Publish Plugin to BinTray'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'publishSibylPluginPublicationToBintrayRepository -Ppublish=1 --stacktrace'
          build-root-directory: 'plugin'
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}

      - name: 'Publish Plugin Marker to BinTray'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'publishSibylDatabasePluginMarkerMavenPublicationToBintrayRepository -Ppublish=1 -PPOM_ARTIFACT_ID=moe.nikky.sibyl.database.gradle.plugin --stacktrace'
          build-root-directory: 'plugin'
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
